<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="HSM2SM" nsURI="platform:/resource/HSM2SM/model/HSM2SM.ecore"
    nsPrefix="HSM2SM">
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine2StateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/HSM2SM/metamodels/hsm.ecore#//StateMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/HSM2SM/metamodels/sm.ecore#//StateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OwnedState2ownedState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/HSM2SM/metamodels/hsm.ecore#//StateMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/HSM2SM/metamodels/sm.ecore#//StateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State2State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/HSM2SM/metamodels/hsm.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/HSM2SM/metamodels/sm.ecore#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition2Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/HSM2SM/metamodels/hsm.ecore#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/HSM2SM/metamodels/sm.ecore#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OwnedTransition2ownedTransition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/HSM2SM/metamodels/hsm.ecore#//StateMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/HSM2SM/metamodels/sm.ecore#//StateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionSource2TransitionSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/HSM2SM/metamodels/hsm.ecore#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/HSM2SM/metamodels/sm.ecore#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionTarget2TransitionTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/HSM2SM/metamodels/hsm.ecore#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/HSM2SM/metamodels/sm.ecore#//Transition"/>
  </eClassifiers>
</ecore:EPackage>
